export const KPI_Types = {
  PROFITABILITY: "PROFITABILITY",
  LEADERSHIP: "LEADERSHIP",
  KNOWLEDGE_MANAGEMENT: "KNOWLEDGE MANAGEMENT",
  TEAMWORK: "TEAMWORK",
  FIRM_DEVELOPMENT: "FIRM DEVELOPMENT",
  TECHNICAL_SKILLS: "TECHNICAL SKILLS",
  BUSINESS_DEVELOPMENT: "BUSINESS DEVELOPMENT"
}