name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for electron-builder to detect tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build and publish Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use PAT with repo access
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          npm run electron:build
        working-directory: ./client

      - name: Publish Release (if draft)
        if: always()  # Runs even if previous steps fail
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for gh CLI auth
        run: |
          gh release edit ${{ github.ref_name }} --draft=false