name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use default secret
        run: npm run electron:build
        working-directory: ./client